"""add_batted_ball_analytics_and_ballpark_gps

Revision ID: 0727f609ab47
Revises: bd66d35e1e9e
Create Date: 2026-04-04 00:58:57.450571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0727f609ab47'
down_revision: Union[str, Sequence[str], None] = 'bd66d35e1e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statcast_batted_balls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('stand', sa.String(length=1), nullable=False),
    sa.Column('launch_speed', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('launch_angle', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('hc_x', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('hc_y', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('spray_angle', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hit_distance_sc', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('bb_type', sa.String(length=20), nullable=True),
    sa.Column('events', sa.String(length=40), nullable=True),
    sa.Column('is_rhb', sa.Integer(), nullable=False),
    sa.Column('temperature_f', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('pressure_hpa', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('relative_humidity', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_speed_mph', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_direction_deg', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('precipitation_mm_hr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cf_bearing_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('air_density_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('tailwind_component', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('baseline_distance', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('total_delta', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('delta_density', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('delta_wind', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('delta_precip', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('environmental_factor', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('spin_contact_factor', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statcast_batted_balls_batter_id'), 'statcast_batted_balls', ['batter_id'], unique=False)
    op.create_index(op.f('ix_statcast_batted_balls_game_date'), 'statcast_batted_balls', ['game_date'], unique=False)
    op.create_index(op.f('ix_statcast_batted_balls_game_pk'), 'statcast_batted_balls', ['game_pk'], unique=False)
    op.create_index(op.f('ix_statcast_batted_balls_pitcher_id'), 'statcast_batted_balls', ['pitcher_id'], unique=False)
    op.create_index(op.f('ix_statcast_batted_balls_venue_id'), 'statcast_batted_balls', ['venue_id'], unique=False)
    op.add_column('ballparks', sa.Column('hp_lat', sa.Float(), nullable=True))
    op.add_column('ballparks', sa.Column('hp_lon', sa.Float(), nullable=True))
    op.add_column('ballparks', sa.Column('pm_lat', sa.Float(), nullable=True))
    op.add_column('ballparks', sa.Column('pm_lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ballparks', 'pm_lon')
    op.drop_column('ballparks', 'pm_lat')
    op.drop_column('ballparks', 'hp_lon')
    op.drop_column('ballparks', 'hp_lat')
    op.drop_index(op.f('ix_statcast_batted_balls_venue_id'), table_name='statcast_batted_balls')
    op.drop_index(op.f('ix_statcast_batted_balls_pitcher_id'), table_name='statcast_batted_balls')
    op.drop_index(op.f('ix_statcast_batted_balls_game_pk'), table_name='statcast_batted_balls')
    op.drop_index(op.f('ix_statcast_batted_balls_game_date'), table_name='statcast_batted_balls')
    op.drop_index(op.f('ix_statcast_batted_balls_batter_id'), table_name='statcast_batted_balls')
    op.drop_table('statcast_batted_balls')
    # ### end Alembic commands ###
