"""Add missing Statcast columns travel distance roof enums

Revision ID: 0f15454fc2b9
Revises: 0727f609ab47
Create Date: 2026-04-06 03:31:42.725886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f15454fc2b9'
down_revision: Union[str, Sequence[str], None] = '0727f609ab47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    gametype = sa.Enum('REGULAR_SEASON', 'POSTSEASON', 'SPRING_TRAINING', 'EXHIBITION', 'ALL_STAR', name='gametype')
    gametype.create(op.get_bind(), checkfirst=True)
    surfacetype = sa.Enum('GRASS', 'TURF', name='surfacetype')
    surfacetype.create(op.get_bind(), checkfirst=True)
    rooftype = sa.Enum('OPEN', 'CLOSED', 'RETRACTABLE', name='rooftype')
    rooftype.create(op.get_bind(), checkfirst=True)
    
    op.add_column('ballparks', sa.Column('surface_type', surfacetype, nullable=True))
    op.add_column('ballparks', sa.Column('roof_type', rooftype, nullable=True))
    op.drop_column('ballparks', 'roof')
    op.add_column('game_results', sa.Column('home_travel_distance_km', sa.Float(), nullable=True))
    op.add_column('game_results', sa.Column('away_travel_distance_km', sa.Float(), nullable=True))
    op.alter_column('game_results', 'game_type',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_foreign_key(None, 'game_results', 'ballparks', ['ballpark_id'], ['id'])
    op.add_column('pitch_events', sa.Column('type', sa.String(length=5), nullable=True))
    op.alter_column('pitch_events', 'pitch_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('pitch_events', 'events',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('pitch_events', 'description',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('pitch_events', 'stand',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.alter_column('pitch_events', 'p_throws',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.alter_column('player_rolling_features', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_prf_game_date'), table_name='player_rolling_features')
    op.drop_index(op.f('ix_prf_player_id'), table_name='player_rolling_features')
    op.drop_index(op.f('ix_prf_season'), table_name='player_rolling_features')
    op.create_index(op.f('ix_player_rolling_features_game_date'), 'player_rolling_features', ['game_date'], unique=False)
    op.create_index(op.f('ix_player_rolling_features_player_id'), 'player_rolling_features', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_rolling_features_season'), 'player_rolling_features', ['season'], unique=False)
    op.alter_column('retrosheet_events', 'gametype',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('REGULAR_SEASON', 'POSTSEASON', 'SPRING_TRAINING', 'EXHIBITION', 'ALL_STAR', name='gametype'),
               existing_nullable=True,
               postgresql_using="CASE WHEN gametype IN ('regular', 'R') THEN 'REGULAR_SEASON' WHEN gametype IN ('postseason', 'P', 'F', 'D', 'L', 'W', 'wildcard') THEN 'POSTSEASON' WHEN gametype IN ('allstar', 'A', 'all_star') THEN 'ALL_STAR' WHEN gametype IN ('spring', 'S', 'spring_training') THEN 'SPRING_TRAINING' WHEN gametype IN ('exhibition', 'E') THEN 'EXHIBITION' ELSE 'REGULAR_SEASON' END::gametype")
    op.add_column('statcast_raw', sa.Column('release_pos_x', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('release_pos_z', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('spin_dir', sa.String(length=50), nullable=True))
    op.add_column('statcast_raw', sa.Column('break_angle_deprecated', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('break_length_deprecated', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('zone', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('stand', sa.String(length=50), nullable=True))
    op.add_column('statcast_raw', sa.Column('p_throws', sa.String(length=50), nullable=True))
    op.add_column('statcast_raw', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('statcast_raw', sa.Column('hit_location', sa.String(length=50), nullable=True))
    op.add_column('statcast_raw', sa.Column('balls', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('strikes', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('game_year', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('on_3b', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('on_2b', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('on_1b', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('outs_when_up', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('tfs_deprecated', sa.String(length=50), nullable=True))
    op.add_column('statcast_raw', sa.Column('tfs_zulu_deprecated', sa.String(length=50), nullable=True))
    op.add_column('statcast_raw', sa.Column('umpire', sa.String(length=50), nullable=True))
    op.add_column('statcast_raw', sa.Column('sv_id', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('vx0', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('vy0', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('vz0', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('ax', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('ay', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('az', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('sz_top', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('sz_bot', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('effective_speed', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('release_extension', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('fielder_2', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('fielder_3', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('fielder_4', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('fielder_5', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('fielder_6', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('fielder_7', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('fielder_8', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('fielder_9', sa.String(length=20), nullable=True))
    op.add_column('statcast_raw', sa.Column('release_pos_y', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('woba_value', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('woba_denom', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('babip_value', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('iso_value', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('home_score', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('away_score', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('bat_score', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('fld_score', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('if_fielding_alignment', sa.String(length=50), nullable=True))
    op.add_column('statcast_raw', sa.Column('of_fielding_alignment', sa.String(length=50), nullable=True))
    op.add_column('statcast_raw', sa.Column('spin_axis', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('estimated_slg_using_speedangle', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('delta_pitcher_run_exp', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('hyper_speed', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('home_score_diff', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('bat_score_diff', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('home_win_exp', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('bat_win_exp', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('age_pit_legacy', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('age_bat_legacy', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('age_pit', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('age_bat', sa.Integer(), nullable=True))
    op.add_column('statcast_raw', sa.Column('n_thruorder_pitcher', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('n_priorpa_thisgame_player_at_bat', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('pitcher_days_since_prev_game', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('batter_days_since_prev_game', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('pitcher_days_until_next_game', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('batter_days_until_next_game', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('api_break_z_with_gravity', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('api_break_x_arm', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('api_break_x_batter_in', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('arm_angle', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('attack_angle', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('attack_direction', sa.String(length=50), nullable=True))
    op.add_column('statcast_raw', sa.Column('swing_path_tilt', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('intercept_ball_minus_batter_pos_x_inches', sa.Numeric(precision=7, scale=3), nullable=True))
    op.add_column('statcast_raw', sa.Column('intercept_ball_minus_batter_pos_y_inches', sa.Numeric(precision=7, scale=3), nullable=True))
    op.alter_column('umpire_scorecards', 'game_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('REGULAR_SEASON', 'POSTSEASON', 'SPRING_TRAINING', 'EXHIBITION', 'ALL_STAR', name='gametype'),
               existing_nullable=True,
               postgresql_using="CASE WHEN game_type IN ('regular', 'R') THEN 'REGULAR_SEASON' WHEN game_type IN ('postseason', 'P', 'F', 'D', 'L', 'W', 'wildcard') THEN 'POSTSEASON' WHEN game_type IN ('allstar', 'A', 'all_star') THEN 'ALL_STAR' WHEN game_type IN ('spring', 'S', 'spring_training') THEN 'SPRING_TRAINING' WHEN game_type IN ('exhibition', 'E') THEN 'EXHIBITION' ELSE 'REGULAR_SEASON' END::gametype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('umpire_scorecards', 'game_type',
               existing_type=sa.Enum('REGULAR_SEASON', 'POSTSEASON', 'SPRING_TRAINING', 'EXHIBITION', 'ALL_STAR', name='gametype'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.drop_column('statcast_raw', 'intercept_ball_minus_batter_pos_y_inches')
    op.drop_column('statcast_raw', 'intercept_ball_minus_batter_pos_x_inches')
    op.drop_column('statcast_raw', 'swing_path_tilt')
    op.drop_column('statcast_raw', 'attack_direction')
    op.drop_column('statcast_raw', 'attack_angle')
    op.drop_column('statcast_raw', 'arm_angle')
    op.drop_column('statcast_raw', 'api_break_x_batter_in')
    op.drop_column('statcast_raw', 'api_break_x_arm')
    op.drop_column('statcast_raw', 'api_break_z_with_gravity')
    op.drop_column('statcast_raw', 'batter_days_until_next_game')
    op.drop_column('statcast_raw', 'pitcher_days_until_next_game')
    op.drop_column('statcast_raw', 'batter_days_since_prev_game')
    op.drop_column('statcast_raw', 'pitcher_days_since_prev_game')
    op.drop_column('statcast_raw', 'n_priorpa_thisgame_player_at_bat')
    op.drop_column('statcast_raw', 'n_thruorder_pitcher')
    op.drop_column('statcast_raw', 'age_bat')
    op.drop_column('statcast_raw', 'age_pit')
    op.drop_column('statcast_raw', 'age_bat_legacy')
    op.drop_column('statcast_raw', 'age_pit_legacy')
    op.drop_column('statcast_raw', 'bat_win_exp')
    op.drop_column('statcast_raw', 'home_win_exp')
    op.drop_column('statcast_raw', 'bat_score_diff')
    op.drop_column('statcast_raw', 'home_score_diff')
    op.drop_column('statcast_raw', 'hyper_speed')
    op.drop_column('statcast_raw', 'delta_pitcher_run_exp')
    op.drop_column('statcast_raw', 'estimated_slg_using_speedangle')
    op.drop_column('statcast_raw', 'spin_axis')
    op.drop_column('statcast_raw', 'of_fielding_alignment')
    op.drop_column('statcast_raw', 'if_fielding_alignment')
    op.drop_column('statcast_raw', 'fld_score')
    op.drop_column('statcast_raw', 'bat_score')
    op.drop_column('statcast_raw', 'away_score')
    op.drop_column('statcast_raw', 'home_score')
    op.drop_column('statcast_raw', 'iso_value')
    op.drop_column('statcast_raw', 'babip_value')
    op.drop_column('statcast_raw', 'woba_denom')
    op.drop_column('statcast_raw', 'woba_value')
    op.drop_column('statcast_raw', 'release_pos_y')
    op.drop_column('statcast_raw', 'fielder_9')
    op.drop_column('statcast_raw', 'fielder_8')
    op.drop_column('statcast_raw', 'fielder_7')
    op.drop_column('statcast_raw', 'fielder_6')
    op.drop_column('statcast_raw', 'fielder_5')
    op.drop_column('statcast_raw', 'fielder_4')
    op.drop_column('statcast_raw', 'fielder_3')
    op.drop_column('statcast_raw', 'fielder_2')
    op.drop_column('statcast_raw', 'release_extension')
    op.drop_column('statcast_raw', 'effective_speed')
    op.drop_column('statcast_raw', 'sz_bot')
    op.drop_column('statcast_raw', 'sz_top')
    op.drop_column('statcast_raw', 'az')
    op.drop_column('statcast_raw', 'ay')
    op.drop_column('statcast_raw', 'ax')
    op.drop_column('statcast_raw', 'vz0')
    op.drop_column('statcast_raw', 'vy0')
    op.drop_column('statcast_raw', 'vx0')
    op.drop_column('statcast_raw', 'sv_id')
    op.drop_column('statcast_raw', 'umpire')
    op.drop_column('statcast_raw', 'tfs_zulu_deprecated')
    op.drop_column('statcast_raw', 'tfs_deprecated')
    op.drop_column('statcast_raw', 'outs_when_up')
    op.drop_column('statcast_raw', 'on_1b')
    op.drop_column('statcast_raw', 'on_2b')
    op.drop_column('statcast_raw', 'on_3b')
    op.drop_column('statcast_raw', 'game_year')
    op.drop_column('statcast_raw', 'strikes')
    op.drop_column('statcast_raw', 'balls')
    op.drop_column('statcast_raw', 'hit_location')
    op.drop_column('statcast_raw', 'type')
    op.drop_column('statcast_raw', 'p_throws')
    op.drop_column('statcast_raw', 'stand')
    op.drop_column('statcast_raw', 'zone')
    op.drop_column('statcast_raw', 'break_length_deprecated')
    op.drop_column('statcast_raw', 'break_angle_deprecated')
    op.drop_column('statcast_raw', 'spin_dir')
    op.drop_column('statcast_raw', 'release_pos_z')
    op.drop_column('statcast_raw', 'release_pos_x')
    op.alter_column('retrosheet_events', 'gametype',
               existing_type=sa.Enum('REGULAR_SEASON', 'POSTSEASON', 'SPRING_TRAINING', 'EXHIBITION', 'ALL_STAR', name='gametype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_player_rolling_features_season'), table_name='player_rolling_features')
    op.drop_index(op.f('ix_player_rolling_features_player_id'), table_name='player_rolling_features')
    op.drop_index(op.f('ix_player_rolling_features_game_date'), table_name='player_rolling_features')
    op.create_index(op.f('ix_prf_season'), 'player_rolling_features', ['season'], unique=False)
    op.create_index(op.f('ix_prf_player_id'), 'player_rolling_features', ['player_id'], unique=False)
    op.create_index(op.f('ix_prf_game_date'), 'player_rolling_features', ['game_date'], unique=False)
    op.alter_column('player_rolling_features', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('pitch_events', 'p_throws',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    op.alter_column('pitch_events', 'stand',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    op.alter_column('pitch_events', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('pitch_events', 'events',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('pitch_events', 'pitch_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.drop_column('pitch_events', 'type')
    op.drop_constraint(None, 'game_results', type_='foreignkey')  # type: ignore
    op.alter_column('game_results', 'game_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.drop_column('game_results', 'away_travel_distance_km')
    op.drop_column('game_results', 'home_travel_distance_km')
    op.add_column('ballparks', sa.Column('roof', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('ballparks', 'roof_type')
    op.drop_column('ballparks', 'surface_type')
    
    surfacetype = sa.Enum('GRASS', 'TURF', name='surfacetype')
    surfacetype.drop(op.get_bind(), checkfirst=True)
    rooftype = sa.Enum('OPEN', 'CLOSED', 'RETRACTABLE', name='rooftype')
    rooftype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
