"""Add fb_speed to statcast_player_game_logs

Revision ID: 28968e0adcc3
Revises: 7d0e646bb164
Create Date: 2026-04-11 22:54:49.068905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28968e0adcc3'
down_revision: Union[str, Sequence[str], None] = '7d0e646bb164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statcast_player_game_logs', sa.Column('fb_speed', sa.Float(), nullable=True))
    op.alter_column('uranium_eval_history', 'fold_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('uranium_eval_history', 'accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('uranium_eval_history', 'auc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('uranium_eval_history', 'log_loss_val',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('uranium_eval_history', 'brier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('uranium_shap_global', 'mean_shap')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uranium_shap_global', sa.Column('mean_shap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('uranium_eval_history', 'brier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('uranium_eval_history', 'log_loss_val',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('uranium_eval_history', 'auc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('uranium_eval_history', 'accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('uranium_eval_history', 'fold_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('statcast_player_game_logs', 'fb_speed')
    # ### end Alembic commands ###
