"""Add GumboPitchORM for canonical timestamps

Revision ID: 35363c48a49a
Revises: 6379d468a810
Create Date: 2026-04-06 14:08:31.352279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35363c48a49a'
down_revision: Union[str, Sequence[str], None] = '6379d468a810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gumbo_pitches',
    sa.Column('game_pk', sa.BigInteger(), nullable=False),
    sa.Column('at_bat_number', sa.SmallInteger(), nullable=False),
    sa.Column('pitch_number', sa.SmallInteger(), nullable=False),
    sa.Column('play_id', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('game_pk', 'at_bat_number', 'pitch_number')
    )
    op.create_index(op.f('ix_gumbo_pitches_play_id'), 'gumbo_pitches', ['play_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gumbo_pitches_play_id'), table_name='gumbo_pitches')
    op.drop_table('gumbo_pitches')
    # ### end Alembic commands ###
