"""Add platoon splits to Silver Layer

Revision ID: 358c69f418d3
Revises: 7eed0d179873
Create Date: 2026-04-06 15:04:01.916645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358c69f418d3'
down_revision: Union[str, Sequence[str], None] = '7eed0d179873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statcast_player_game_logs', sa.Column('xwoba_vs_rh', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('pa_vs_rh', sa.SmallInteger(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('xwoba_vs_lh', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('pa_vs_lh', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statcast_player_game_logs', 'pa_vs_lh')
    op.drop_column('statcast_player_game_logs', 'xwoba_vs_lh')
    op.drop_column('statcast_player_game_logs', 'pa_vs_rh')
    op.drop_column('statcast_player_game_logs', 'xwoba_vs_rh')
    # ### end Alembic commands ###
