"""add_statcast_quant_features

Revision ID: 3a5f40389270
Revises: 1e9e29e72de1
Create Date: 2026-04-03 05:15:54.817707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5f40389270'
down_revision: Union[str, Sequence[str], None] = '1e9e29e72de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statcast_quant_features',
    sa.Column('game_pk', sa.BigInteger(), nullable=False),
    sa.Column('at_bat_number', sa.SmallInteger(), nullable=False),
    sa.Column('pitch_number', sa.SmallInteger(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('batter', sa.Integer(), nullable=False),
    sa.Column('pitcher', sa.Integer(), nullable=False),
    sa.Column('xba_raw', sa.Float(), nullable=True),
    sa.Column('xba_calibrated', sa.Float(), nullable=True),
    sa.Column('xwoba_raw', sa.Float(), nullable=True),
    sa.Column('xwoba_calibrated', sa.Float(), nullable=True),
    sa.Column('launch_quality', sa.SmallInteger(), nullable=True),
    sa.Column('pfx_x_std', sa.Float(), nullable=True),
    sa.Column('pfx_z_std', sa.Float(), nullable=True),
    sa.Column('release_speed_std', sa.Float(), nullable=True),
    sa.Column('spray_angle_deg', sa.Float(), nullable=True),
    sa.Column('hit_x_ft', sa.Float(), nullable=True),
    sa.Column('hit_y_ft', sa.Float(), nullable=True),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('baseline_window_days', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game_pk', 'at_bat_number', 'pitch_number'], ['statcast_raw.game_pk', 'statcast_raw.at_bat_number', 'statcast_raw.pitch_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_pk', 'at_bat_number', 'pitch_number'),
    sa.UniqueConstraint('game_pk', 'at_bat_number', 'pitch_number', name='uq_statcast_quant_features_pk')
    )
    op.create_index(op.f('ix_statcast_quant_features_batter'), 'statcast_quant_features', ['batter'], unique=False)
    op.create_index(op.f('ix_statcast_quant_features_game_date'), 'statcast_quant_features', ['game_date'], unique=False)
    op.create_index(op.f('ix_statcast_quant_features_pitcher'), 'statcast_quant_features', ['pitcher'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statcast_quant_features_pitcher'), table_name='statcast_quant_features')
    op.drop_index(op.f('ix_statcast_quant_features_game_date'), table_name='statcast_quant_features')
    op.drop_index(op.f('ix_statcast_quant_features_batter'), table_name='statcast_quant_features')
    op.drop_table('statcast_quant_features')
    # ### end Alembic commands ###
