"""Expand Gold Layer with 25+ sharp predictive features

Revision ID: 41e5c1d2968c
Revises: 358c69f418d3
Create Date: 2026-04-06 15:05:54.808677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e5c1d2968c'
down_revision: Union[str, Sequence[str], None] = '358c69f418d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_rolling_features', sa.Column('ema_pitcher_xwoba_3g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('ema_pitcher_xwoba_7g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('ema_edge_pct_3g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('ema_velo_degradation_3g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('std_pitcher_xwoba_15g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('std_edge_pct_15g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('std_release_pos_z_15g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('fatigue_index_7d', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('fatigue_index_14d', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('delta_spin_rate_3g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('delta_extension_3g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('delta_fb_velo_3g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('ema_batter_xwoba_3g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('ema_batter_xwoba_7g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('ema_bat_speed_3g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('ema_attack_angle_3g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('ema_chase_pct_3g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('ema_iz_whiff_pct_3g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('std_batter_xwoba_15g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('std_launch_angle_15g', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('seasonal_xwoba_vs_rh', sa.Float(), nullable=True))
    op.add_column('player_rolling_features', sa.Column('seasonal_xwoba_vs_lh', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_rolling_features', 'seasonal_xwoba_vs_lh')
    op.drop_column('player_rolling_features', 'seasonal_xwoba_vs_rh')
    op.drop_column('player_rolling_features', 'std_launch_angle_15g')
    op.drop_column('player_rolling_features', 'std_batter_xwoba_15g')
    op.drop_column('player_rolling_features', 'ema_iz_whiff_pct_3g')
    op.drop_column('player_rolling_features', 'ema_chase_pct_3g')
    op.drop_column('player_rolling_features', 'ema_attack_angle_3g')
    op.drop_column('player_rolling_features', 'ema_bat_speed_3g')
    op.drop_column('player_rolling_features', 'ema_batter_xwoba_7g')
    op.drop_column('player_rolling_features', 'ema_batter_xwoba_3g')
    op.drop_column('player_rolling_features', 'delta_fb_velo_3g')
    op.drop_column('player_rolling_features', 'delta_extension_3g')
    op.drop_column('player_rolling_features', 'delta_spin_rate_3g')
    op.drop_column('player_rolling_features', 'fatigue_index_14d')
    op.drop_column('player_rolling_features', 'fatigue_index_7d')
    op.drop_column('player_rolling_features', 'std_release_pos_z_15g')
    op.drop_column('player_rolling_features', 'std_edge_pct_15g')
    op.drop_column('player_rolling_features', 'std_pitcher_xwoba_15g')
    op.drop_column('player_rolling_features', 'ema_velo_degradation_3g')
    op.drop_column('player_rolling_features', 'ema_edge_pct_3g')
    op.drop_column('player_rolling_features', 'ema_pitcher_xwoba_7g')
    op.drop_column('player_rolling_features', 'ema_pitcher_xwoba_3g')
    # ### end Alembic commands ###
