"""add_pitch_events_unique_constraint

Revision ID: 4a4133ba9fa2
Revises: cd108a384964
Create Date: 2026-03-30 15:57:56.042149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4133ba9fa2'
down_revision: Union[str, Sequence[str], None] = 'cd108a384964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_events', sa.Column('at_bat_number', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_pitch_events_game_ab_pitch', 'pitch_events', ['game_id', 'at_bat_number', 'pitch_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pitch_events_game_ab_pitch', 'pitch_events', type_='unique')
    op.drop_column('pitch_events', 'at_bat_number')
    # ### end Alembic commands ###
