"""Add UraniumSimulatedPlayerPropsORM

Revision ID: 4fe0de4e2cb0
Revises: 28968e0adcc3
Create Date: 2026-04-12 06:10:44.205227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe0de4e2cb0'
down_revision: Union[str, Sequence[str], None] = '28968e0adcc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uranium_simulated_player_props',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('stat_type', sa.String(length=20), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('prob_over_0_5', sa.Float(), nullable=True),
    sa.Column('prob_over_1_5', sa.Float(), nullable=True),
    sa.Column('prob_over_2_5', sa.Float(), nullable=True),
    sa.Column('prob_over_3_5', sa.Float(), nullable=True),
    sa.Column('prob_over_4_5', sa.Float(), nullable=True),
    sa.Column('p10', sa.Float(), nullable=True),
    sa.Column('p90', sa.Float(), nullable=True),
    sa.Column('trials', sa.Integer(), nullable=False),
    sa.Column('simulated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_pk', 'player_id', 'stat_type', name='uq_simulated_player_prop_game_player_stat')
    )
    op.create_index(op.f('ix_uranium_simulated_player_props_game_pk'), 'uranium_simulated_player_props', ['game_pk'], unique=False)
    op.create_index(op.f('ix_uranium_simulated_player_props_player_id'), 'uranium_simulated_player_props', ['player_id'], unique=False)
    op.create_index(op.f('ix_uranium_simulated_player_props_stat_type'), 'uranium_simulated_player_props', ['stat_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uranium_simulated_player_props_stat_type'), table_name='uranium_simulated_player_props')
    op.drop_index(op.f('ix_uranium_simulated_player_props_player_id'), table_name='uranium_simulated_player_props')
    op.drop_index(op.f('ix_uranium_simulated_player_props_game_pk'), table_name='uranium_simulated_player_props')
    op.drop_table('uranium_simulated_player_props')
    # ### end Alembic commands ###
