"""add game_lineups table for starting lineup tracking

Revision ID: 5c033dcb5ad6
Revises: 41e5c1d2968c
Create Date: 2026-04-06 17:19:52.255248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c033dcb5ad6'
down_revision: Union[str, Sequence[str], None] = '41e5c1d2968c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_lineups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('team_side', sa.String(length=4), nullable=False),
    sa.Column('batting_order', sa.SmallInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_pk', 'team_side', 'batting_order', name='uq_game_lineup_slot')
    )
    op.create_index(op.f('ix_game_lineups_game_date'), 'game_lineups', ['game_date'], unique=False)
    op.create_index(op.f('ix_game_lineups_game_pk'), 'game_lineups', ['game_pk'], unique=False)
    op.create_index(op.f('ix_game_lineups_player_id'), 'game_lineups', ['player_id'], unique=False)
    op.create_index('ix_lineup_game_date', 'game_lineups', ['game_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lineup_game_date', table_name='game_lineups')
    op.drop_index(op.f('ix_game_lineups_player_id'), table_name='game_lineups')
    op.drop_index(op.f('ix_game_lineups_game_pk'), table_name='game_lineups')
    op.drop_index(op.f('ix_game_lineups_game_date'), table_name='game_lineups')
    op.drop_table('game_lineups')
    # ### end Alembic commands ###
