"""refine manager hook schema and add registry

Revision ID: 5ded81ccce6b
Revises: 6c98f281fd64
Create Date: 2026-04-08 01:16:56.385582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ded81ccce6b'
down_revision: Union[str, Sequence[str], None] = '6c98f281fd64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_manager_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('retrosheet_game_id', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('home_away', sa.String(length=10), nullable=False),
    sa.Column('doubleheader_num', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('manager_stint_start', sa.Date(), nullable=False),
    sa.Column('manager_tenure_day', sa.Integer(), nullable=False),
    sa.Column('days_since_manager_change', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_pk', 'team_id', name='uq_registry_game_team'),
    sa.UniqueConstraint('retrosheet_game_id', 'team_id', name='uq_registry_retro_team')
    )
    op.create_index(op.f('ix_game_manager_registry_game_date'), 'game_manager_registry', ['game_date'], unique=False)
    op.create_index(op.f('ix_game_manager_registry_game_pk'), 'game_manager_registry', ['game_pk'], unique=False)
    op.create_index(op.f('ix_game_manager_registry_manager_id'), 'game_manager_registry', ['manager_id'], unique=False)
    op.create_index(op.f('ix_game_manager_registry_retrosheet_game_id'), 'game_manager_registry', ['retrosheet_game_id'], unique=False)
    op.create_index(op.f('ix_game_manager_registry_season'), 'game_manager_registry', ['season'], unique=False)
    op.create_index(op.f('ix_game_manager_registry_team_id'), 'game_manager_registry', ['team_id'], unique=False)
    op.add_column('manager_hook_events', sa.Column('game_pk', sa.Integer(), nullable=False))
    op.add_column('manager_hook_events', sa.Column('team_id', sa.Integer(), nullable=False))
    op.add_column('manager_hook_events', sa.Column('opponent_id', sa.Integer(), nullable=False))
    op.add_column('manager_hook_events', sa.Column('pitches_thrown', sa.Integer(), nullable=False))
    op.add_column('manager_hook_events', sa.Column('tto_at_hook', sa.Integer(), nullable=False))
    op.add_column('manager_hook_events', sa.Column('score_diff_at_hook', sa.Integer(), nullable=False))
    op.add_column('manager_hook_events', sa.Column('base_state_at_hook', sa.Integer(), nullable=False))
    op.add_column('manager_hook_events', sa.Column('leverage_index_at_hook', sa.Float(), nullable=False))
    op.add_column('manager_hook_events', sa.Column('manager_tenure_day', sa.Integer(), nullable=False))
    op.add_column('manager_hook_events', sa.Column('days_since_manager_change', sa.Integer(), nullable=False))
    op.add_column('manager_hook_events', sa.Column('bullpen_availability_snapshot_id', sa.Integer(), nullable=True))
    op.add_column('manager_hook_events', sa.Column('hook_reason', sa.String(length=50), nullable=True))
    op.add_column('manager_hook_events', sa.Column('removed_before_next_batter', sa.Boolean(), nullable=False))
    op.alter_column('manager_hook_events', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_manager_hook_events_game_id'), table_name='manager_hook_events')
    op.drop_constraint(op.f('uq_manager_hook_game_pitcher'), 'manager_hook_events', type_='unique')
    op.create_unique_constraint('uq_manager_hook_game_pitcher', 'manager_hook_events', ['game_pk', 'pitcher_id'])
    op.create_index(op.f('ix_manager_hook_events_game_pk'), 'manager_hook_events', ['game_pk'], unique=False)
    op.create_index(op.f('ix_manager_hook_events_team_id'), 'manager_hook_events', ['team_id'], unique=False)
    op.drop_column('manager_hook_events', 'hook_before_3rd_tto')
    op.drop_column('manager_hook_events', 'is_home')
    op.drop_column('manager_hook_events', 'tto')
    op.drop_column('manager_hook_events', 'strikeouts')
    op.drop_column('manager_hook_events', 'walks_allowed')
    op.drop_column('manager_hook_events', 'hr_allowed')
    op.drop_column('manager_hook_events', 'team_abbr')
    op.drop_column('manager_hook_events', 'hits_allowed')
    op.drop_column('manager_hook_events', 'runs_allowed')
    op.drop_column('manager_hook_events', 'manager_name')
    op.drop_column('manager_hook_events', 'pa_count')
    op.drop_column('manager_hook_events', 'pitch_count')
    op.drop_column('manager_hook_events', 'score_diff')
    op.drop_column('manager_hook_events', 'runners_on')
    op.drop_column('manager_hook_events', 'inherited_runners')
    op.drop_column('manager_hook_events', 'was_quality_start')
    op.drop_column('manager_hook_events', 'game_id')
    op.add_column('manager_hook_profiles', sa.Column('avg_ip_per_start', sa.Float(), nullable=False))
    op.add_column('manager_hook_profiles', sa.Column('avg_hook_inning', sa.Float(), nullable=False))
    op.add_column('manager_hook_profiles', sa.Column('pull_when_over_90_pitches_pct', sa.Float(), nullable=False))
    op.add_column('manager_hook_profiles', sa.Column('quick_hook_high_leverage_pct', sa.Float(), nullable=False))
    op.add_column('manager_hook_profiles', sa.Column('bullpen_protective_pct', sa.Float(), nullable=False))
    op.drop_column('manager_hook_profiles', 'avg_sp_innings')
    op.drop_column('manager_hook_profiles', 'median_sp_pitch_count')
    op.drop_column('manager_hook_profiles', 'quick_hook_under_80_pitches_pct')
    op.drop_column('manager_hook_profiles', 'long_hook_over_100_pitches_pct')
    op.drop_column('manager_hook_profiles', 'pull_with_deficit_pct')
    op.add_column('team_managers', sa.Column('effective_start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_managers', 'effective_start_date')
    op.add_column('manager_hook_profiles', sa.Column('pull_with_deficit_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('manager_hook_profiles', sa.Column('long_hook_over_100_pitches_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('manager_hook_profiles', sa.Column('quick_hook_under_80_pitches_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('manager_hook_profiles', sa.Column('median_sp_pitch_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('manager_hook_profiles', sa.Column('avg_sp_innings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('manager_hook_profiles', 'bullpen_protective_pct')
    op.drop_column('manager_hook_profiles', 'quick_hook_high_leverage_pct')
    op.drop_column('manager_hook_profiles', 'pull_when_over_90_pitches_pct')
    op.drop_column('manager_hook_profiles', 'avg_hook_inning')
    op.drop_column('manager_hook_profiles', 'avg_ip_per_start')
    op.add_column('manager_hook_events', sa.Column('game_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('was_quality_start', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('inherited_runners', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('runners_on', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('score_diff', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('pitch_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('pa_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('manager_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('manager_hook_events', sa.Column('runs_allowed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('hits_allowed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('team_abbr', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('hr_allowed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('walks_allowed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('strikeouts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('tto', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('is_home', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('manager_hook_events', sa.Column('hook_before_3rd_tto', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_manager_hook_events_team_id'), table_name='manager_hook_events')
    op.drop_index(op.f('ix_manager_hook_events_game_pk'), table_name='manager_hook_events')
    op.drop_constraint('uq_manager_hook_game_pitcher', 'manager_hook_events', type_='unique')
    op.create_unique_constraint(op.f('uq_manager_hook_game_pitcher'), 'manager_hook_events', ['game_id', 'pitcher_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_manager_hook_events_game_id'), 'manager_hook_events', ['game_id'], unique=False)
    op.alter_column('manager_hook_events', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('manager_hook_events', 'removed_before_next_batter')
    op.drop_column('manager_hook_events', 'hook_reason')
    op.drop_column('manager_hook_events', 'bullpen_availability_snapshot_id')
    op.drop_column('manager_hook_events', 'days_since_manager_change')
    op.drop_column('manager_hook_events', 'manager_tenure_day')
    op.drop_column('manager_hook_events', 'leverage_index_at_hook')
    op.drop_column('manager_hook_events', 'base_state_at_hook')
    op.drop_column('manager_hook_events', 'score_diff_at_hook')
    op.drop_column('manager_hook_events', 'tto_at_hook')
    op.drop_column('manager_hook_events', 'pitches_thrown')
    op.drop_column('manager_hook_events', 'opponent_id')
    op.drop_column('manager_hook_events', 'team_id')
    op.drop_column('manager_hook_events', 'game_pk')
    op.drop_index(op.f('ix_game_manager_registry_team_id'), table_name='game_manager_registry')
    op.drop_index(op.f('ix_game_manager_registry_season'), table_name='game_manager_registry')
    op.drop_index(op.f('ix_game_manager_registry_retrosheet_game_id'), table_name='game_manager_registry')
    op.drop_index(op.f('ix_game_manager_registry_manager_id'), table_name='game_manager_registry')
    op.drop_index(op.f('ix_game_manager_registry_game_pk'), table_name='game_manager_registry')
    op.drop_index(op.f('ix_game_manager_registry_game_date'), table_name='game_manager_registry')
    op.drop_table('game_manager_registry')
    # ### end Alembic commands ###
