"""add_openmeteo_weather_progression_table

Revision ID: 6128fcd4a4ca
Revises: d9bb56c48af6
Create Date: 2026-04-01 01:38:19.415575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6128fcd4a4ca'
down_revision: Union[str, Sequence[str], None] = 'd9bb56c48af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openmeteo_weather_progression',
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('temp_t0_f', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_speed_t0', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_dir_t0', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('temp_t1_f', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_speed_t1', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_dir_t1', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('temp_t2_f', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_speed_t2', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_dir_t2', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('temp_t3_f', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_speed_t3', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_dir_t3', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('temp_t4_f', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_speed_t4', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_dir_t4', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('humidity_t0', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('precip_t0_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pressure_t0_hpa', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('cloud_cover_t0_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('temp_delta_game', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('temp_min_game', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_speed_max_game', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_dir_variance_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('headwind_t0_mph', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('headwind_t3_mph', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('headwind_delta_game', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('crosswind_t0_mph', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('wind_shift_gt_45deg', sa.Boolean(), nullable=True),
    sa.Column('temp_drop_gt_10f', sa.Boolean(), nullable=True),
    sa.Column('precip_any_game', sa.Boolean(), nullable=True),
    sa.Column('forecast_temp_f', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('forecast_wind_speed_mph', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('forecast_wind_dir_deg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('forecast_headwind_mph', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('forecast_crosswind_mph', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('forecast_precip_prob', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('forecast_cloud_cover_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('forecast_source', sa.String(length=50), nullable=True),
    sa.Column('delta_temp_f', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('delta_wind_speed_mph', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('delta_headwind_mph', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('delta_precip_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('era5_model_used', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_results.game_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('openmeteo_weather_progression')
    # ### end Alembic commands ###
