"""Remove dead Statcast columns

Revision ID: 6379d468a810
Revises: 0f15454fc2b9
Create Date: 2026-04-06 12:23:58.505863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6379d468a810'
down_revision: Union[str, Sequence[str], None] = '0f15454fc2b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statcast_raw', 'spin_rate_deprecated')
    op.drop_column('statcast_raw', 'blue_color')
    op.drop_column('statcast_raw', 'pybaseball_version')
    op.drop_column('statcast_raw', 'spin_dir')
    op.drop_column('statcast_raw', 'sv_id')
    op.drop_column('statcast_raw', 'home_team_1')
    op.drop_column('statcast_raw', 'pitcher_1')
    op.drop_column('statcast_raw', 'umpire')
    op.drop_column('statcast_raw', 'break_length_deprecated')
    op.drop_column('statcast_raw', 'break_angle_deprecated')
    op.drop_column('statcast_raw', 'tfs_deprecated')
    op.drop_column('statcast_raw', 'industrial_color')
    op.drop_column('statcast_raw', 'at_bat_number_1')
    op.drop_column('statcast_raw', 'tfs_zulu_deprecated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statcast_raw', sa.Column('tfs_zulu_deprecated', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('at_bat_number_1', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('industrial_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('tfs_deprecated', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('break_angle_deprecated', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('break_length_deprecated', sa.NUMERIC(precision=7, scale=3), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('umpire', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('pitcher_1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('home_team_1', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('sv_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('spin_dir', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('pybaseball_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('blue_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('statcast_raw', sa.Column('spin_rate_deprecated', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
