"""init_db

Revision ID: 64bfc2b18406
Revises: 
Create Date: 2026-03-30 07:42:08.227418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGENUM


# revision identifiers, used by Alembic.
revision: str = '64bfc2b18406'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Handle PostgreSQL Enums gracefully (if they already exist)
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        for enum_name, values in [
            ('transactionstatus', ('PENDING', 'SETTLED', 'CANCELLED', 'ADJUSTMENT')),
            ('gamestatus', ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'POSTPONED'))
        ]:
            exists = bind.execute(sa.text(f"SELECT 1 FROM pg_type WHERE typname = '{enum_name}'")).fetchone()
            if not exists:
                sa.Enum(*values, name=enum_name).create(bind)

    op.create_table('bankroll_ledger',
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('status', PGENUM('PENDING', 'SETTLED', 'CANCELLED', 'ADJUSTMENT', name='transactionstatus', create_type=False), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('game_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_bankroll_ledger_game_id'), 'bankroll_ledger', ['game_id'], unique=False)
    op.create_index(op.f('ix_bankroll_ledger_timestamp'), 'bankroll_ledger', ['timestamp'], unique=False)
    op.create_table('game_results',
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=50), nullable=False),
    sa.Column('away_team', sa.String(length=50), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('home_rest_days', sa.Integer(), nullable=True),
    sa.Column('away_rest_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_game_results_game_date'), 'game_results', ['game_date'], unique=False)
    op.create_table('graded_games',
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=50), nullable=False),
    sa.Column('away_team', sa.String(length=50), nullable=False),
    sa.Column('home_pitcher', sa.String(length=100), nullable=True),
    sa.Column('away_pitcher', sa.String(length=100), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', PGENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'POSTPONED', name='gamestatus', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_graded_games_date'), 'graded_games', ['date'], unique=False)
    op.create_table('historical_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_data_date'), 'historical_data', ['date'], unique=False)
    op.create_index(op.f('ix_historical_data_player_id'), 'historical_data', ['player_id'], unique=False)
    op.create_table('live_odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('sportsbook', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_odds_game_id'), 'live_odds', ['game_id'], unique=False)
    # Re-adding the rest from the original file for completeness
    op.create_index(op.f('ix_live_odds_timestamp'), 'live_odds', ['timestamp'], unique=False)
    op.create_table('pitch_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('release_speed', sa.Float(), nullable=True),
    sa.Column('release_spin_rate', sa.Float(), nullable=True),
    sa.Column('pfx_x', sa.Float(), nullable=True),
    sa.Column('pfx_z', sa.Float(), nullable=True),
    sa.Column('plate_x', sa.Float(), nullable=True),
    sa.Column('plate_z', sa.Float(), nullable=True),
    sa.Column('launch_speed', sa.Float(), nullable=True),
    sa.Column('launch_angle', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitch_events_batter_id'), 'pitch_events', ['batter_id'], unique=False)
    op.create_index(op.f('ix_pitch_events_game_date'), 'pitch_events', ['game_date'], unique=False)
    op.create_index(op.f('ix_pitch_events_game_id'), 'pitch_events', ['game_id'], unique=False)
    op.create_index(op.f('ix_pitch_events_pitcher_id'), 'pitch_events', ['pitcher_id'], unique=False)
    op.create_table('player_rolling_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('feature_name', sa.String(length=50), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_rolling_features_date'), 'player_rolling_features', ['date'], unique=False)
    op.create_index(op.f('ix_player_rolling_features_player_id'), 'player_rolling_features', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_rolling_features_player_id'), table_name='player_rolling_features')
    op.drop_index(op.f('ix_player_rolling_features_date'), table_name='player_rolling_features')
    op.drop_table('player_rolling_features')
    op.drop_index(op.f('ix_pitch_events_pitcher_id'), table_name='pitch_events')
    op.drop_index(op.f('ix_pitch_events_game_id'), table_name='pitch_events')
    op.drop_index(op.f('ix_pitch_events_game_date'), table_name='pitch_events')
    op.drop_index(op.f('ix_pitch_events_batter_id'), table_name='pitch_events')
    op.drop_table('pitch_events')
    op.drop_index(op.f('ix_live_odds_timestamp'), table_name='live_odds')
    op.drop_index(op.f('ix_live_odds_game_id'), table_name='live_odds')
    op.drop_table('live_odds')
    op.drop_index(op.f('ix_historical_data_player_id'), table_name='historical_data')
    op.drop_index(op.f('ix_historical_data_date'), table_name='historical_data')
    op.drop_table('historical_data')
    op.drop_index(op.f('ix_graded_games_date'), table_name='graded_games')
    op.drop_table('graded_games')
    op.drop_index(op.f('ix_game_results_game_date'), table_name='game_results')
    op.drop_table('game_results')
    op.drop_index(op.f('ix_bankroll_ledger_timestamp'), table_name='bankroll_ledger')
    op.drop_index(op.f('ix_bankroll_ledger_game_id'), table_name='bankroll_ledger')
    op.drop_table('bankroll_ledger')
    # ### end Alembic commands ###
