"""add manager hook events and profiles tables

Revision ID: 6c98f281fd64
Revises: d497d9276a16
Create Date: 2026-04-07 15:00:10.865724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c98f281fd64'
down_revision: Union[str, Sequence[str], None] = 'd497d9276a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_hook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_abbr', sa.String(length=5), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('pitcher_id', sa.String(length=20), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('outs_at_hook', sa.Integer(), nullable=False),
    sa.Column('pitch_count', sa.Integer(), nullable=False),
    sa.Column('pa_count', sa.Integer(), nullable=False),
    sa.Column('tto', sa.Integer(), nullable=False),
    sa.Column('score_diff', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('runners_on', sa.Integer(), nullable=False),
    sa.Column('inherited_runners', sa.Integer(), nullable=False),
    sa.Column('hits_allowed', sa.Integer(), nullable=False),
    sa.Column('walks_allowed', sa.Integer(), nullable=False),
    sa.Column('strikeouts', sa.Integer(), nullable=False),
    sa.Column('runs_allowed', sa.Integer(), nullable=False),
    sa.Column('hr_allowed', sa.Integer(), nullable=False),
    sa.Column('was_quality_start', sa.Boolean(), nullable=False),
    sa.Column('hook_before_3rd_tto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'pitcher_id', name='uq_manager_hook_game_pitcher')
    )
    op.create_index(op.f('ix_manager_hook_events_game_date'), 'manager_hook_events', ['game_date'], unique=False)
    op.create_index(op.f('ix_manager_hook_events_game_id'), 'manager_hook_events', ['game_id'], unique=False)
    op.create_index(op.f('ix_manager_hook_events_manager_id'), 'manager_hook_events', ['manager_id'], unique=False)
    op.create_index(op.f('ix_manager_hook_events_pitcher_id'), 'manager_hook_events', ['pitcher_id'], unique=False)
    op.create_index(op.f('ix_manager_hook_events_season'), 'manager_hook_events', ['season'], unique=False)
    op.create_table('manager_hook_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('manager_name', sa.String(length=100), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('total_hooks', sa.Integer(), nullable=False),
    sa.Column('total_sp_starts', sa.Integer(), nullable=False),
    sa.Column('avg_sp_pitch_count', sa.Float(), nullable=False),
    sa.Column('median_sp_pitch_count', sa.Float(), nullable=False),
    sa.Column('avg_sp_innings', sa.Float(), nullable=False),
    sa.Column('pull_before_3rd_tto_pct', sa.Float(), nullable=False),
    sa.Column('pull_with_lead_pct', sa.Float(), nullable=False),
    sa.Column('pull_with_deficit_pct', sa.Float(), nullable=False),
    sa.Column('quick_hook_under_80_pitches_pct', sa.Float(), nullable=False),
    sa.Column('long_hook_over_100_pitches_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'season', name='uq_manager_hook_profile_mgr_season')
    )
    op.create_index(op.f('ix_manager_hook_profiles_manager_id'), 'manager_hook_profiles', ['manager_id'], unique=False)
    op.create_index(op.f('ix_manager_hook_profiles_season'), 'manager_hook_profiles', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manager_hook_profiles_season'), table_name='manager_hook_profiles')
    op.drop_index(op.f('ix_manager_hook_profiles_manager_id'), table_name='manager_hook_profiles')
    op.drop_table('manager_hook_profiles')
    op.drop_index(op.f('ix_manager_hook_events_season'), table_name='manager_hook_events')
    op.drop_index(op.f('ix_manager_hook_events_pitcher_id'), table_name='manager_hook_events')
    op.drop_index(op.f('ix_manager_hook_events_manager_id'), table_name='manager_hook_events')
    op.drop_index(op.f('ix_manager_hook_events_game_id'), table_name='manager_hook_events')
    op.drop_index(op.f('ix_manager_hook_events_game_date'), table_name='manager_hook_events')
    op.drop_table('manager_hook_events')
    # ### end Alembic commands ###
