"""add team_elo_history table

Revision ID: 7ed1aab77ff8
Revises: 5c033dcb5ad6
Create Date: 2026-04-07 03:45:18.155296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed1aab77ff8'
down_revision: Union[str, Sequence[str], None] = '5c033dcb5ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_elo_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.BigInteger(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('elo_pre', sa.Float(), nullable=False),
    sa.Column('elo_post', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_pk', 'team_id', 'is_home', name='uq_team_elo_history_row')
    )
    op.create_index(op.f('ix_team_elo_history_game_date'), 'team_elo_history', ['game_date'], unique=False)
    op.create_index(op.f('ix_team_elo_history_game_pk'), 'team_elo_history', ['game_pk'], unique=False)
    op.create_index(op.f('ix_team_elo_history_team_id'), 'team_elo_history', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_elo_history_team_id'), table_name='team_elo_history')
    op.drop_index(op.f('ix_team_elo_history_game_pk'), table_name='team_elo_history')
    op.drop_index(op.f('ix_team_elo_history_game_date'), table_name='team_elo_history')
    op.drop_table('team_elo_history')
    # ### end Alembic commands ###
