"""Add Silver Layer metrics

Revision ID: 7eed0d179873
Revises: 35363c48a49a
Create Date: 2026-04-06 14:13:13.242711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eed0d179873'
down_revision: Union[str, Sequence[str], None] = '35363c48a49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statcast_player_game_logs', sa.Column('avg_release_extension', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('avg_spin_rate', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('avg_spin_axis', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('std_arm_angle', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('std_release_pos_z', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('edge_pct', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('fastball_velo_degradation', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('hard_hits_allowed', sa.SmallInteger(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('avg_bat_speed', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('avg_swing_length', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('avg_attack_angle', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('std_launch_angle', sa.Float(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('in_zone_whiff_count', sa.SmallInteger(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('chase_count', sa.SmallInteger(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('sweet_spots', sa.SmallInteger(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('hard_hits', sa.SmallInteger(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('pull_count', sa.SmallInteger(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('center_count', sa.SmallInteger(), nullable=True))
    op.add_column('statcast_player_game_logs', sa.Column('oppo_count', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statcast_player_game_logs', 'oppo_count')
    op.drop_column('statcast_player_game_logs', 'center_count')
    op.drop_column('statcast_player_game_logs', 'pull_count')
    op.drop_column('statcast_player_game_logs', 'hard_hits')
    op.drop_column('statcast_player_game_logs', 'sweet_spots')
    op.drop_column('statcast_player_game_logs', 'chase_count')
    op.drop_column('statcast_player_game_logs', 'in_zone_whiff_count')
    op.drop_column('statcast_player_game_logs', 'std_launch_angle')
    op.drop_column('statcast_player_game_logs', 'avg_attack_angle')
    op.drop_column('statcast_player_game_logs', 'avg_swing_length')
    op.drop_column('statcast_player_game_logs', 'avg_bat_speed')
    op.drop_column('statcast_player_game_logs', 'hard_hits_allowed')
    op.drop_column('statcast_player_game_logs', 'fastball_velo_degradation')
    op.drop_column('statcast_player_game_logs', 'edge_pct')
    op.drop_column('statcast_player_game_logs', 'std_release_pos_z')
    op.drop_column('statcast_player_game_logs', 'std_arm_angle')
    op.drop_column('statcast_player_game_logs', 'avg_spin_axis')
    op.drop_column('statcast_player_game_logs', 'avg_spin_rate')
    op.drop_column('statcast_player_game_logs', 'avg_release_extension')
    # ### end Alembic commands ###
