"""add pipeline_heartbeat table

Revision ID: a1b2c3d4e5f6
Revises: cca8107f5621
Create Date: 2026-07-23 23:45:00.000000

Hand-written (not autogenerated) to avoid the pre-existing schema drift that
autogenerate picks up from statcast_raw_* partitions and fadegoblin's tables,
which aren't declared in SQLAlchemy metadata as such.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'cca8107f5621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'pipeline_heartbeat',
        sa.Column('job_name', sa.String(length=50), nullable=False),
        sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_status', sa.String(length=20), nullable=False),
        sa.Column('details', sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint('job_name'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('pipeline_heartbeat')
