"""add_statcast_raw_table

Revision ID: ab4376df88e8
Revises: 6dcdc2f3fe3a
Create Date: 2026-04-03 02:12:44.784459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4376df88e8'
down_revision: Union[str, Sequence[str], None] = '6dcdc2f3fe3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statcast_raw',
    sa.Column('game_pk', sa.BigInteger(), nullable=False),
    sa.Column('at_bat_number', sa.SmallInteger(), nullable=False),
    sa.Column('pitch_number', sa.SmallInteger(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=3), nullable=False),
    sa.Column('away_team', sa.String(length=3), nullable=False),
    sa.Column('inning', sa.SmallInteger(), nullable=True),
    sa.Column('inning_topbot', sa.String(length=3), nullable=True),
    sa.Column('batter', sa.Integer(), nullable=False),
    sa.Column('pitcher', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('hc_x', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('hc_y', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('bb_type', sa.String(length=20), nullable=True),
    sa.Column('events', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('launch_speed', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('launch_angle', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('launch_speed_angle', sa.SmallInteger(), nullable=True),
    sa.Column('estimated_ba_using_speedangle', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('estimated_woba_using_speedangle', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('pitch_type', sa.String(length=5), nullable=True),
    sa.Column('release_speed', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('release_spin_rate', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('pfx_x', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('pfx_z', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('plate_x', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('plate_z', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pybaseball_version', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('game_pk', 'at_bat_number', 'pitch_number')
    )
    op.create_index(op.f('ix_statcast_raw_batter'), 'statcast_raw', ['batter'], unique=False)
    op.create_index(op.f('ix_statcast_raw_game_date'), 'statcast_raw', ['game_date'], unique=False)
    op.create_index(op.f('ix_statcast_raw_pitcher'), 'statcast_raw', ['pitcher'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statcast_raw_pitcher'), table_name='statcast_raw')
    op.drop_index(op.f('ix_statcast_raw_game_date'), table_name='statcast_raw')
    op.drop_index(op.f('ix_statcast_raw_batter'), table_name='statcast_raw')
    op.drop_table('statcast_raw')
    # ### end Alembic commands ###
