"""add_silver_layer_tables

Revision ID: b2e290580bc8
Revises: 3a5f40389270
Create Date: 2026-04-03 13:36:34.088739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e290580bc8'
down_revision: Union[str, Sequence[str], None] = '3a5f40389270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> sa.Text | None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statcast_player_game_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('pitches', sa.SmallInteger(), nullable=True),
    sa.Column('strikes', sa.SmallInteger(), nullable=True),
    sa.Column('whiffs', sa.SmallInteger(), nullable=True),
    sa.Column('k', sa.SmallInteger(), nullable=True),
    sa.Column('bb', sa.SmallInteger(), nullable=True),
    sa.Column('avg_release_speed', sa.Float(), nullable=True),
    sa.Column('avg_pfx_x', sa.Float(), nullable=True),
    sa.Column('avg_pfx_z', sa.Float(), nullable=True),
    sa.Column('avg_pitcher_xwoba', sa.Float(), nullable=True),
    sa.Column('pas', sa.SmallInteger(), nullable=True),
    sa.Column('abs', sa.SmallInteger(), nullable=True),
    sa.Column('hits', sa.SmallInteger(), nullable=True),
    sa.Column('batter_k', sa.SmallInteger(), nullable=True),
    sa.Column('batter_bb', sa.SmallInteger(), nullable=True),
    sa.Column('barrels', sa.SmallInteger(), nullable=True),
    sa.Column('avg_launch_speed', sa.Float(), nullable=True),
    sa.Column('avg_launch_angle', sa.Float(), nullable=True),
    sa.Column('avg_batter_xwoba', sa.Float(), nullable=True),
    sa.Column('summarized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_pk', 'player_id', 'role', name='uq_statcast_player_game_log')
    )
    op.create_index(op.f('ix_statcast_player_game_logs_game_date'), 'statcast_player_game_logs', ['game_date'], unique=False)
    op.create_index(op.f('ix_statcast_player_game_logs_game_pk'), 'statcast_player_game_logs', ['game_pk'], unique=False)
    op.create_index(op.f('ix_statcast_player_game_logs_player_id'), 'statcast_player_game_logs', ['player_id'], unique=False)
    
    op.create_table('statcast_process_registry',
    sa.Column('target_table', sa.String(length=50), nullable=False),
    sa.Column('last_processed_ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('target_table')
    )
    
    # op.create_unique_constraint('uq_statcast_quant_features_pk', 'statcast_quant_features', ['game_pk', 'at_bat_number', 'pitch_number'])
    # ### end Alembic commands ###


def downgrade() -> sa.Text | None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_statcast_quant_features_pk', 'statcast_quant_features', type_='unique')
    op.drop_table('statcast_process_registry')
    op.drop_index(op.f('ix_statcast_player_game_logs_player_id'), table_name='statcast_player_game_logs')
    op.drop_index(op.f('ix_statcast_player_game_logs_game_pk'), table_name='statcast_player_game_logs')
    op.drop_index(op.f('ix_statcast_player_game_logs_game_date'), table_name='statcast_player_game_logs')
    op.drop_table('statcast_player_game_logs')
    # ### end Alembic commands ###
