"""add_pitch_events_statcast_columns

Revision ID: b5532a3cf0be
Revises: 64bfc2b18406
Create Date: 2026-03-30 14:23:40.455555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5532a3cf0be'
down_revision: Union[str, Sequence[str], None] = '64bfc2b18406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_events', sa.Column('pitch_type', sa.String(length=5), nullable=True))
    op.add_column('pitch_events', sa.Column('stand', sa.String(length=1), nullable=True))
    op.add_column('pitch_events', sa.Column('p_throws', sa.String(length=1), nullable=True))
    op.add_column('pitch_events', sa.Column('description', sa.String(length=50), nullable=True))
    op.add_column('pitch_events', sa.Column('events', sa.String(length=50), nullable=True))
    op.add_column('pitch_events', sa.Column('release_extension', sa.Float(), nullable=True))
    op.add_column('pitch_events', sa.Column('effective_speed', sa.Float(), nullable=True))
    op.add_column('pitch_events', sa.Column('pitch_number', sa.Integer(), nullable=True))
    op.add_column('pitch_events', sa.Column('inning', sa.Integer(), nullable=True))
    op.add_column('pitch_events', sa.Column('zone', sa.Integer(), nullable=True))
    op.add_column('pitch_events', sa.Column('bb_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch_events', 'bb_type')
    op.drop_column('pitch_events', 'zone')
    op.drop_column('pitch_events', 'inning')
    op.drop_column('pitch_events', 'pitch_number')
    op.drop_column('pitch_events', 'effective_speed')
    op.drop_column('pitch_events', 'release_extension')
    op.drop_column('pitch_events', 'events')
    op.drop_column('pitch_events', 'description')
    op.drop_column('pitch_events', 'p_throws')
    op.drop_column('pitch_events', 'stand')
    op.drop_column('pitch_events', 'pitch_type')
    # ### end Alembic commands ###
