"""Sync UmpireScorecardORM schema expansion

Revision ID: bc8ef141bfb8
Revises: c83f762706ad
Create Date: 2026-03-31 04:30:14.927160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8ef141bfb8'
down_revision: Union[str, Sequence[str], None] = 'c83f762706ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umpire_scorecards', sa.Column('game_pk', sa.Integer(), nullable=False))
    op.add_column('umpire_scorecards', sa.Column('game_date', sa.Date(), nullable=False))
    op.add_column('umpire_scorecards', sa.Column('game_type', sa.String(length=5), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('home_team', sa.String(length=5), nullable=False))
    op.add_column('umpire_scorecards', sa.Column('away_team', sa.String(length=5), nullable=False))
    op.add_column('umpire_scorecards', sa.Column('home_score', sa.Integer(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('away_score', sa.Integer(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('called_pitches', sa.Integer(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('called_correct', sa.Integer(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('called_wrong', sa.Integer(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('x_overall_accuracy', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('accuracy_above_x', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('baseline_x_correct_calls', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('x_correct_calls', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('correct_calls_above_x', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('home_batter_impact', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('home_pitcher_impact', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('away_batter_impact', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('away_pitcher_impact', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('total_run_impact', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('n_overturned', sa.Integer(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('n_challenged', sa.Integer(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('challenge_success_rate', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('n_overturned_home', sa.Integer(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('n_challenged_home', sa.Integer(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('n_overturned_away', sa.Integer(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('n_challenged_away', sa.Integer(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('abs_away_a', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('abs_away_b', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('abs_away_c', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('abs_away_d', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('abs_home_a', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('abs_home_b', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('abs_home_c', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('abs_home_d', sa.Float(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('fully_valid', sa.Boolean(), nullable=True))
    op.add_column('umpire_scorecards', sa.Column('num_pitches_no_data', sa.Integer(), nullable=True))
    op.alter_column('umpire_scorecards', 'game_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_umpire_scorecards_game_date'), 'umpire_scorecards', ['game_date'], unique=False)
    op.create_index(op.f('ix_umpire_scorecards_game_pk'), 'umpire_scorecards', ['game_pk'], unique=False)
    op.create_unique_constraint('uq_umpire_scorecards_game_pk', 'umpire_scorecards', ['game_pk'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_umpire_scorecards_game_pk', 'umpire_scorecards', type_='unique')
    op.drop_index(op.f('ix_umpire_scorecards_game_pk'), table_name='umpire_scorecards')
    op.drop_index(op.f('ix_umpire_scorecards_game_date'), table_name='umpire_scorecards')
    op.alter_column('umpire_scorecards', 'game_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('umpire_scorecards', 'num_pitches_no_data')
    op.drop_column('umpire_scorecards', 'fully_valid')
    op.drop_column('umpire_scorecards', 'abs_home_d')
    op.drop_column('umpire_scorecards', 'abs_home_c')
    op.drop_column('umpire_scorecards', 'abs_home_b')
    op.drop_column('umpire_scorecards', 'abs_home_a')
    op.drop_column('umpire_scorecards', 'abs_away_d')
    op.drop_column('umpire_scorecards', 'abs_away_c')
    op.drop_column('umpire_scorecards', 'abs_away_b')
    op.drop_column('umpire_scorecards', 'abs_away_a')
    op.drop_column('umpire_scorecards', 'n_challenged_away')
    op.drop_column('umpire_scorecards', 'n_overturned_away')
    op.drop_column('umpire_scorecards', 'n_challenged_home')
    op.drop_column('umpire_scorecards', 'n_overturned_home')
    op.drop_column('umpire_scorecards', 'challenge_success_rate')
    op.drop_column('umpire_scorecards', 'n_challenged')
    op.drop_column('umpire_scorecards', 'n_overturned')
    op.drop_column('umpire_scorecards', 'total_run_impact')
    op.drop_column('umpire_scorecards', 'away_pitcher_impact')
    op.drop_column('umpire_scorecards', 'away_batter_impact')
    op.drop_column('umpire_scorecards', 'home_pitcher_impact')
    op.drop_column('umpire_scorecards', 'home_batter_impact')
    op.drop_column('umpire_scorecards', 'correct_calls_above_x')
    op.drop_column('umpire_scorecards', 'x_correct_calls')
    op.drop_column('umpire_scorecards', 'baseline_x_correct_calls')
    op.drop_column('umpire_scorecards', 'accuracy_above_x')
    op.drop_column('umpire_scorecards', 'x_overall_accuracy')
    op.drop_column('umpire_scorecards', 'called_wrong')
    op.drop_column('umpire_scorecards', 'called_correct')
    op.drop_column('umpire_scorecards', 'called_pitches')
    op.drop_column('umpire_scorecards', 'away_score')
    op.drop_column('umpire_scorecards', 'home_score')
    op.drop_column('umpire_scorecards', 'away_team')
    op.drop_column('umpire_scorecards', 'home_team')
    op.drop_column('umpire_scorecards', 'game_type')
    op.drop_column('umpire_scorecards', 'game_date')
    op.drop_column('umpire_scorecards', 'game_pk')
    # ### end Alembic commands ###
