"""add_hp_bearing_to_ballparks

Revision ID: bc91727ec276
Revises: dbc4357804f3
Create Date: 2026-03-31 21:34:17.186809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc91727ec276'
down_revision: Union[str, Sequence[str], None] = 'dbc4357804f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballparks', sa.Column('hp_bearing_deg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ballparks', 'hp_bearing_deg')
    # ### end Alembic commands ###
