"""Add umpire scorecards and fix schema gaps

Revision ID: c83f762706ad
Revises: ed838f038ed2
Create Date: 2026-03-31 01:24:41.995705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83f762706ad'
down_revision: Union[str, Sequence[str], None] = 'ed838f038ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Fix game_results Primary Key and ID column
    bind = op.get_bind()
    
    # 1. Create sequence if it doesn't exist
    op.execute("CREATE SEQUENCE IF NOT EXISTS game_results_id_seq")
    
    # 2. Add default to id column
    op.execute("ALTER TABLE game_results ALTER COLUMN id SET DEFAULT nextval('game_results_id_seq')")
    
    # 3. Populate existing rows with IDs
    op.execute("UPDATE game_results SET id = nextval('game_results_id_seq') WHERE id IS NULL OR id = 0")
    
    # 4. Fix PK Constraint: Drop old PK on game_id and add on id
    # First, find the constraint name (usually game_results_pkey)
    result = bind.execute(sa.text("""
        SELECT conname FROM pg_constraint 
        WHERE conrelid = 'game_results'::regclass AND contype = 'p'
    """)).fetchone()
    
    if result:
        op.drop_constraint(result[0], 'game_results', type_='primary')
    
    op.create_primary_key('game_results_pkey', 'game_results', ['id'])
    
    # 5. Ensure game_id is UNIQUE (since it's a unique field in the model)
    # Check if index exists already (Alembic might have detected it)
    # op.create_unique_constraint('uq_game_results_game_id', 'game_results', ['game_id'])

    op.create_table('retrosheet_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('play_number', sa.Integer(), nullable=False),
    sa.Column('event_text', sa.String(length=255), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('top_bot', sa.Integer(), nullable=False),
    sa.Column('vis_home', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=10), nullable=False),
    sa.Column('bat_team', sa.String(length=5), nullable=False),
    sa.Column('pit_team', sa.String(length=5), nullable=False),
    sa.Column('score_v', sa.Integer(), nullable=False),
    sa.Column('score_h', sa.Integer(), nullable=False),
    sa.Column('batter_id', sa.String(length=20), nullable=False),
    sa.Column('pitcher_id', sa.String(length=20), nullable=False),
    sa.Column('lp', sa.Integer(), nullable=False),
    sa.Column('bat_f', sa.Integer(), nullable=False),
    sa.Column('batter_hand', sa.String(length=1), nullable=True),
    sa.Column('pitcher_hand', sa.String(length=1), nullable=True),
    sa.Column('balls', sa.Integer(), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.Column('count_text', sa.String(length=5), nullable=True),
    sa.Column('pitches', sa.String(length=50), nullable=True),
    sa.Column('nump', sa.Integer(), nullable=True),
    sa.Column('pa_flag', sa.Integer(), nullable=False),
    sa.Column('ab_flag', sa.Integer(), nullable=False),
    sa.Column('single', sa.Integer(), nullable=False),
    sa.Column('double_flag', sa.Integer(), nullable=False),
    sa.Column('triple', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('sh', sa.Integer(), nullable=False),
    sa.Column('sf', sa.Integer(), nullable=False),
    sa.Column('hbp', sa.Integer(), nullable=False),
    sa.Column('walk', sa.Integer(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('xi', sa.Integer(), nullable=False),
    sa.Column('roe', sa.Integer(), nullable=False),
    sa.Column('fc', sa.Integer(), nullable=False),
    sa.Column('othout', sa.Integer(), nullable=False),
    sa.Column('noout', sa.Integer(), nullable=False),
    sa.Column('bip', sa.Integer(), nullable=False),
    sa.Column('bunt', sa.Integer(), nullable=False),
    sa.Column('ground', sa.Integer(), nullable=False),
    sa.Column('fly', sa.Integer(), nullable=False),
    sa.Column('line_flag', sa.Integer(), nullable=False),
    sa.Column('iw', sa.Integer(), nullable=False),
    sa.Column('gdp', sa.Integer(), nullable=False),
    sa.Column('othdp', sa.Integer(), nullable=False),
    sa.Column('tp', sa.Integer(), nullable=False),
    sa.Column('fle', sa.Integer(), nullable=False),
    sa.Column('wp', sa.Integer(), nullable=False),
    sa.Column('pb', sa.Integer(), nullable=False),
    sa.Column('bk', sa.Integer(), nullable=False),
    sa.Column('oa', sa.Integer(), nullable=False),
    sa.Column('di', sa.Integer(), nullable=False),
    sa.Column('sb2', sa.Integer(), nullable=False),
    sa.Column('sb3', sa.Integer(), nullable=False),
    sa.Column('sbh', sa.Integer(), nullable=False),
    sa.Column('cs2', sa.Integer(), nullable=False),
    sa.Column('cs3', sa.Integer(), nullable=False),
    sa.Column('csh', sa.Integer(), nullable=False),
    sa.Column('pko1', sa.Integer(), nullable=False),
    sa.Column('pko2', sa.Integer(), nullable=False),
    sa.Column('pko3', sa.Integer(), nullable=False),
    sa.Column('k_safe', sa.Integer(), nullable=False),
    sa.Column('e1', sa.Integer(), nullable=False),
    sa.Column('e2', sa.Integer(), nullable=False),
    sa.Column('e3', sa.Integer(), nullable=False),
    sa.Column('e4', sa.Integer(), nullable=False),
    sa.Column('e5', sa.Integer(), nullable=False),
    sa.Column('e6', sa.Integer(), nullable=False),
    sa.Column('e7', sa.Integer(), nullable=False),
    sa.Column('e8', sa.Integer(), nullable=False),
    sa.Column('e9', sa.Integer(), nullable=False),
    sa.Column('outs_pre', sa.Integer(), nullable=False),
    sa.Column('outs_post', sa.Integer(), nullable=False),
    sa.Column('br1_pre', sa.String(length=20), nullable=True),
    sa.Column('br2_pre', sa.String(length=20), nullable=True),
    sa.Column('br3_pre', sa.String(length=20), nullable=True),
    sa.Column('br1_post', sa.String(length=20), nullable=True),
    sa.Column('br2_post', sa.String(length=20), nullable=True),
    sa.Column('br3_post', sa.String(length=20), nullable=True),
    sa.Column('lob_id1', sa.String(length=20), nullable=True),
    sa.Column('lob_id2', sa.String(length=20), nullable=True),
    sa.Column('lob_id3', sa.String(length=20), nullable=True),
    sa.Column('pr1_pre', sa.String(length=20), nullable=True),
    sa.Column('pr2_pre', sa.String(length=20), nullable=True),
    sa.Column('pr3_pre', sa.String(length=20), nullable=True),
    sa.Column('pr1_post', sa.String(length=20), nullable=True),
    sa.Column('pr2_post', sa.String(length=20), nullable=True),
    sa.Column('pr3_post', sa.String(length=20), nullable=True),
    sa.Column('run_b', sa.String(length=20), nullable=True),
    sa.Column('run1', sa.String(length=20), nullable=True),
    sa.Column('run2', sa.String(length=20), nullable=True),
    sa.Column('run3', sa.String(length=20), nullable=True),
    sa.Column('prun_b', sa.String(length=20), nullable=True),
    sa.Column('prun1', sa.String(length=20), nullable=True),
    sa.Column('prun2', sa.String(length=20), nullable=True),
    sa.Column('prun3', sa.String(length=20), nullable=True),
    sa.Column('ur_b', sa.Integer(), nullable=False),
    sa.Column('ur1', sa.Integer(), nullable=False),
    sa.Column('ur2', sa.Integer(), nullable=False),
    sa.Column('ur3', sa.Integer(), nullable=False),
    sa.Column('rbi_b', sa.Integer(), nullable=False),
    sa.Column('rbi1', sa.Integer(), nullable=False),
    sa.Column('rbi2', sa.Integer(), nullable=False),
    sa.Column('rbi3', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('er', sa.Integer(), nullable=False),
    sa.Column('tur', sa.Integer(), nullable=False),
    sa.Column('f2', sa.String(length=20), nullable=True),
    sa.Column('f3', sa.String(length=20), nullable=True),
    sa.Column('f4', sa.String(length=20), nullable=True),
    sa.Column('f5', sa.String(length=20), nullable=True),
    sa.Column('f6', sa.String(length=20), nullable=True),
    sa.Column('f7', sa.String(length=20), nullable=True),
    sa.Column('f8', sa.String(length=20), nullable=True),
    sa.Column('f9', sa.String(length=20), nullable=True),
    sa.Column('po1', sa.Integer(), nullable=False),
    sa.Column('po2', sa.Integer(), nullable=False),
    sa.Column('po3', sa.Integer(), nullable=False),
    sa.Column('po4', sa.Integer(), nullable=False),
    sa.Column('po5', sa.Integer(), nullable=False),
    sa.Column('po6', sa.Integer(), nullable=False),
    sa.Column('po7', sa.Integer(), nullable=False),
    sa.Column('po8', sa.Integer(), nullable=False),
    sa.Column('po9', sa.Integer(), nullable=False),
    sa.Column('a1', sa.Integer(), nullable=False),
    sa.Column('a2', sa.Integer(), nullable=False),
    sa.Column('a3', sa.Integer(), nullable=False),
    sa.Column('a4', sa.Integer(), nullable=False),
    sa.Column('a5', sa.Integer(), nullable=False),
    sa.Column('a6', sa.Integer(), nullable=False),
    sa.Column('a7', sa.Integer(), nullable=False),
    sa.Column('a8', sa.Integer(), nullable=False),
    sa.Column('a9', sa.Integer(), nullable=False),
    sa.Column('fseq', sa.String(length=20), nullable=True),
    sa.Column('firstf', sa.Integer(), nullable=False),
    sa.Column('loc', sa.String(length=10), nullable=True),
    sa.Column('hittype', sa.String(length=5), nullable=True),
    sa.Column('dpopp', sa.Integer(), nullable=False),
    sa.Column('pivot', sa.Integer(), nullable=False),
    sa.Column('umphome', sa.String(length=50), nullable=True),
    sa.Column('ump1b', sa.String(length=50), nullable=True),
    sa.Column('ump2b', sa.String(length=50), nullable=True),
    sa.Column('ump3b', sa.String(length=50), nullable=True),
    sa.Column('umplf', sa.String(length=50), nullable=True),
    sa.Column('umprf', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gametype', sa.String(length=20), nullable=True),
    sa.Column('pbp', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrosheet_events_date'), 'retrosheet_events', ['date'], unique=False)
    op.create_index(op.f('ix_retrosheet_events_game_id'), 'retrosheet_events', ['game_id'], unique=False)
    op.create_table('umpire_scorecards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('umpire_name', sa.String(length=100), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('consistency', sa.Float(), nullable=False),
    sa.Column('favoritism_home', sa.Float(), nullable=False),
    sa.Column('expected_runs', sa.Float(), nullable=False),
    sa.Column('actual_runs', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_umpire_scorecards_game_id'), 'umpire_scorecards', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_umpire_scorecards_game_id'), table_name='umpire_scorecards')
    op.drop_table('umpire_scorecards')
    op.drop_index(op.f('ix_retrosheet_events_game_id'), table_name='retrosheet_events')
    op.drop_index(op.f('ix_retrosheet_events_date'), table_name='retrosheet_events')
    op.drop_table('retrosheet_events')
    # ### end Alembic commands ###
