"""split_market_into_type_and_outcome

Revision ID: cd108a384964
Revises: b5532a3cf0be
Create Date: 2026-03-30 15:38:45.957484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd108a384964'
down_revision: Union[str, Sequence[str], None] = 'b5532a3cf0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_index(op.f('ix_live_odds_game_id'), table_name='live_odds')
    op.alter_column('live_odds', 'game_id', new_column_name='odds_game_id')
    op.add_column('live_odds', sa.Column('home_team', sa.String(length=50), nullable=True))
    op.add_column('live_odds', sa.Column('away_team', sa.String(length=50), nullable=True))
    op.add_column('live_odds', sa.Column('game_date', sa.Date(), nullable=True))
    op.add_column('live_odds', sa.Column('game_result_id', sa.String(length=50), nullable=True))
    op.add_column('live_odds', sa.Column('market_type', sa.String(length=50), nullable=True))
    op.add_column('live_odds', sa.Column('outcome', sa.String(length=100), nullable=True))
    
    # Backfill rows as requested by user
    op.execute("""
        UPDATE live_odds
        SET market_type = SPLIT_PART(market, ':', 1),
            outcome     = SPLIT_PART(market, ':', 2),
            home_team   = 'Unknown',
            away_team   = 'Unknown',
            game_date   = CURRENT_DATE
    """)

    op.alter_column('live_odds', 'home_team', nullable=False)
    op.alter_column('live_odds', 'away_team', nullable=False)
    op.alter_column('live_odds', 'game_date', nullable=False)
    op.alter_column('live_odds', 'market_type', nullable=False)
    op.alter_column('live_odds', 'outcome', nullable=False)

    op.create_index(op.f('ix_live_odds_game_date'), 'live_odds', ['game_date'], unique=False)
    op.create_index(op.f('ix_live_odds_game_result_id'), 'live_odds', ['game_result_id'], unique=False)
    op.create_index(op.f('ix_live_odds_odds_game_id'), 'live_odds', ['odds_game_id'], unique=False)
    op.drop_column('live_odds', 'market')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_odds', sa.Column('market', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.execute("UPDATE live_odds SET market = CONCAT(market_type, ':', outcome)")
    op.alter_column('live_odds', 'market', nullable=False)
    op.drop_index(op.f('ix_live_odds_odds_game_id'), table_name='live_odds')
    op.drop_index(op.f('ix_live_odds_game_result_id'), table_name='live_odds')
    op.drop_index(op.f('ix_live_odds_game_date'), table_name='live_odds')
    op.drop_column('live_odds', 'outcome')
    op.drop_column('live_odds', 'market_type')
    op.drop_column('live_odds', 'game_result_id')
    op.drop_column('live_odds', 'game_date')
    op.drop_column('live_odds', 'away_team')
    op.drop_column('live_odds', 'home_team')
    op.alter_column('live_odds', 'odds_game_id', new_column_name='game_id')
    op.create_index(op.f('ix_live_odds_game_id'), 'live_odds', ['game_id'], unique=False)
