"""add team_managers table

Revision ID: d497d9276a16
Revises: 85ee0542f0ed
Create Date: 2026-04-07 14:38:27.815106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd497d9276a16'
down_revision: Union[str, Sequence[str], None] = '85ee0542f0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_abbr', sa.String(length=5), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('manager_name', sa.String(length=100), nullable=False),
    sa.Column('jersey_number', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', 'manager_id', name='uq_team_managers_team_season_mgr')
    )
    op.create_index(op.f('ix_team_managers_manager_id'), 'team_managers', ['manager_id'], unique=False)
    op.create_index(op.f('ix_team_managers_season'), 'team_managers', ['season'], unique=False)
    op.create_index(op.f('ix_team_managers_team_id'), 'team_managers', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_managers_team_id'), table_name='team_managers')
    op.drop_index(op.f('ix_team_managers_season'), table_name='team_managers')
    op.drop_index(op.f('ix_team_managers_manager_id'), table_name='team_managers')
    op.drop_table('team_managers')
    # ### end Alembic commands ###
