"""add_player_name_to_transactions

Revision ID: d9bb56c48af6
Revises: 490bc14c8971
Create Date: 2026-03-31 22:26:48.528370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bb56c48af6'
down_revision: Union[str, Sequence[str], None] = '490bc14c8971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_transactions', sa.Column('player_name', sa.String(), nullable=True))
    op.alter_column('player_transactions', 'raw_description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_player_transactions_player_date'), table_name='player_transactions')
    op.drop_index(op.f('idx_player_transactions_team_date'), table_name='player_transactions')
    op.create_index(op.f('ix_player_transactions_player_id'), 'player_transactions', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_transactions_player_name'), 'player_transactions', ['player_name'], unique=False)
    op.create_index(op.f('ix_player_transactions_team_id'), 'player_transactions', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_transactions_team_id'), table_name='player_transactions')
    op.drop_index(op.f('ix_player_transactions_player_name'), table_name='player_transactions')
    op.drop_index(op.f('ix_player_transactions_player_id'), table_name='player_transactions')
    op.create_index(op.f('idx_player_transactions_team_date'), 'player_transactions', ['team_id', 'transaction_date'], unique=False)
    op.create_index(op.f('idx_player_transactions_player_date'), 'player_transactions', ['player_id', 'effective_date'], unique=False)
    op.alter_column('player_transactions', 'raw_description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('player_transactions', 'player_name')
    # ### end Alembic commands ###
