"""add_ballpark_location_fields

Revision ID: dbc4357804f3
Revises: bc8ef141bfb8
Create Date: 2026-03-31 05:40:44.073754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc4357804f3'
down_revision: Union[str, Sequence[str], None] = 'bc8ef141bfb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballparks', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('ballparks', sa.Column('state', sa.String(length=20), nullable=True))
    op.add_column('ballparks', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('ballparks', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ballparks', 'longitude')
    op.drop_column('ballparks', 'latitude')
    op.drop_column('ballparks', 'state')
    op.drop_column('ballparks', 'city')
    # ### end Alembic commands ###
