"""add_pitcher_ids_to_graded_games

Revision ID: e55c77b53e7f
Revises: 4a4133ba9fa2
Create Date: 2026-03-30 18:14:25.130720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55c77b53e7f'
down_revision: Union[str, Sequence[str], None] = '4a4133ba9fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graded_games', sa.Column('home_pitcher_id', sa.Integer(), nullable=True))
    op.add_column('graded_games', sa.Column('away_pitcher_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graded_games', 'away_pitcher_id')
    op.drop_column('graded_games', 'home_pitcher_id')
    # ### end Alembic commands ###
