"""Add ballparks and historical odds

Revision ID: ed838f038ed2
Revises: e55c77b53e7f
Create Date: 2026-03-30 22:16:59.342167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed838f038ed2'
down_revision: Union[str, Sequence[str], None] = 'e55c77b53e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ballparks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=50), nullable=False),
    sa.Column('ballpark', sa.String(length=100), nullable=False),
    sa.Column('left_field', sa.Integer(), nullable=True),
    sa.Column('center_field', sa.Integer(), nullable=True),
    sa.Column('right_field', sa.Integer(), nullable=True),
    sa.Column('min_wall_height', sa.Float(), nullable=True),
    sa.Column('max_wall_height', sa.Float(), nullable=True),
    sa.Column('hr_park_effects', sa.Float(), nullable=True),
    sa.Column('extra_distance', sa.Float(), nullable=True),
    sa.Column('avg_temp', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.Column('roof', sa.Float(), nullable=True),
    sa.Column('daytime', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ballpark')
    )
    op.create_index(op.f('ix_ballparks_team_name'), 'ballparks', ['team_name'], unique=False)
    op.create_table('historical_odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('odds_type', sa.String(length=10), nullable=False),
    sa.Column('home_price', sa.Integer(), nullable=False),
    sa.Column('away_price', sa.Integer(), nullable=False),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_odds_game_id'), 'historical_odds', ['game_id'], unique=False)
    op.drop_index(op.f('ix_graded_games_date'), table_name='graded_games')
    op.drop_table('graded_games')
    op.add_column('game_results', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('game_results', sa.Column('home_pitcher', sa.String(length=100), nullable=True))
    op.add_column('game_results', sa.Column('away_pitcher', sa.String(length=100), nullable=True))
    op.add_column('game_results', sa.Column('home_pitcher_id', sa.Integer(), nullable=True))
    op.add_column('game_results', sa.Column('away_pitcher_id', sa.Integer(), nullable=True))
    op.add_column('game_results', sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'POSTPONED', name='gamestatus'), nullable=False))
    op.add_column('game_results', sa.Column('ballpark_id', sa.Integer(), nullable=True))
    op.alter_column('game_results', 'home_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_results', 'away_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_game_results_game_id'), 'game_results', ['game_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_results_game_id'), table_name='game_results')
    op.alter_column('game_results', 'away_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_results', 'home_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('game_results', 'ballpark_id')
    op.drop_column('game_results', 'status')
    op.drop_column('game_results', 'away_pitcher_id')
    op.drop_column('game_results', 'home_pitcher_id')
    op.drop_column('game_results', 'away_pitcher')
    op.drop_column('game_results', 'home_pitcher')
    op.drop_column('game_results', 'id')
    op.create_table('graded_games',
    sa.Column('game_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('home_team', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('away_team', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('home_pitcher', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('away_pitcher', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('home_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'POSTPONED', name='gamestatus'), autoincrement=False, nullable=False),
    sa.Column('home_pitcher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_pitcher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('game_id', name=op.f('graded_games_pkey'))
    )
    op.create_index(op.f('ix_graded_games_date'), 'graded_games', ['date'], unique=False)
    op.drop_index(op.f('ix_historical_odds_game_id'), table_name='historical_odds')
    op.drop_table('historical_odds')
    op.drop_index(op.f('ix_ballparks_team_name'), table_name='ballparks')
    op.drop_table('ballparks')
    # ### end Alembic commands ###
